### ISSUE TITLE
User guide?

### ISSUE THREAD

**Issue by mehrdadxyz** [dostaji4/EnergyPlus-co-simulation-toolbox#2]
Hi,
Is there any user guide documentation for using this toolbox?
does it support controlling all HVAC loop parameters?

**Comment by dostaji4** [comment]
Hi, 
I'm afraid; the toolbox can make just what PtolemyServer or ExternalInterface of EnergyPlus can do. The toolkit provides communication between Matlab and EnergyPlus. The specification of the IDF file is entirely up to you.  I'm sorry, but I can't answer if it supports "all HVAC loop parameters" because I don't know. I'm not an EnergyPlus expert. Try if your parameters can be cast as ExternalInterface: Schedule, ExternalInterface: Actuator, etc., then it should work! 
Jiri
